// <auto-generated />
using System;
using KitchenFlow.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KitchenFlow.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260804013603_AddPreparedComponentTransactions")]
    partial class AddPreparedComponentTransactions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KitchenFlow.Infrastructure.Persistence.AuditEventRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.ToTable("audit_events", "platform");
                });

            modelBuilder.Entity("KitchenFlow.Infrastructure.Persistence.EquipmentEntryRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Capacity")
                        .HasColumnType("numeric(18,3)");

                    b.Property<string>("CapacityUnit")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ConstraintNote")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomName")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("boolean");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("StableCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId", "StableCode")
                        .IsUnique();

                    b.ToTable("equipment_entries", "profiles", t =>
                        {
                            t.HasCheckConstraint("ck_equipment_capacity", "\"Capacity\" IS NULL OR \"Capacity\" >= 0");
                        });
                });

            modelBuilder.Entity("KitchenFlow.Infrastructure.Persistence.IdempotencyRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ETag")
                        .HasColumnType("text");

                    b.Property<Guid>("Key")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("jsonb");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId", "Scope", "Key")
                        .IsUnique();

                    b.ToTable("idempotency_records", "platform", t =>
                        {
                            t.HasCheckConstraint("ck_idempotency_completion", "(\"CompletedAt\" IS NULL AND \"ResponseBody\" IS NULL AND \"ETag\" IS NULL) OR (\"CompletedAt\" IS NOT NULL AND \"ResponseBody\" IS NOT NULL)");

                            t.HasCheckConstraint("ck_idempotency_status_code", "\"StatusCode\" BETWEEN 200 AND 299");
                        });
                });

            modelBuilder.Entity("KitchenFlow.Infrastructure.Persistence.LotRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvailabilityState")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("ConcurrencyToken")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomLocation")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExpirationProvenance")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("MeasuredUnit")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal?>("MeasuredValue")
                        .HasColumnType("numeric(18,3)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("PackageState")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateOnly?>("PrintedExpirationDate")
                        .HasColumnType("date");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("StorageLocation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ConcurrencyToken")
                        .IsUnique();

                    b.HasIndex("ProductId", "OwnerUserId");

                    b.HasIndex("OwnerUserId", "UpdatedAt", "Id");

                    b.ToTable("lots", "inventory", t =>
                        {
                            t.HasCheckConstraint("ck_lots_availability_state", "\"AvailabilityState\" IS NULL OR \"AvailabilityState\" IN ('Available', 'Low', 'Unavailable')");

                            t.HasCheckConstraint("ck_lots_expiration_provenance", "(\"PrintedExpirationDate\" IS NULL AND \"ExpirationProvenance\" IS NULL) OR (\"PrintedExpirationDate\" IS NOT NULL AND \"ExpirationProvenance\" IS NOT NULL AND \"ExpirationProvenance\" = 'UserEntered')");

                            t.HasCheckConstraint("ck_lots_measured_unit", "\"MeasuredUnit\" IS NULL OR \"MeasuredUnit\" IN ('Gram', 'Milliliter', 'Unit')");

                            t.HasCheckConstraint("ck_lots_measured_value", "\"MeasuredValue\" IS NULL OR \"MeasuredValue\" >= 0");

                            t.HasCheckConstraint("ck_lots_package_state", "\"PackageState\" IS NULL OR \"PackageState\" IN ('Sealed', 'Opened', 'Unknown')");

                            t.HasCheckConstraint("ck_lots_quantity_mode", "(\"MeasuredValue\" IS NOT NULL AND \"MeasuredUnit\" IS NOT NULL AND \"AvailabilityState\" IS NULL) OR (\"MeasuredValue\" IS NULL AND \"MeasuredUnit\" IS NULL AND \"AvailabilityState\" IS NOT NULL)");

                            t.HasCheckConstraint("ck_lots_storage", "(\"StorageLocation\" IN ('Pantry', 'Refrigerator', 'Freezer') AND \"CustomLocation\" IS NULL) OR (\"StorageLocation\" = 'Other' AND \"CustomLocation\" IS NOT NULL AND length(btrim(\"CustomLocation\")) > 0)");
                        });
                });

            modelBuilder.Entity("KitchenFlow.Infrastructure.Persistence.PreferenceEntryRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Presence")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("StableCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId", "Category", "StableCode")
                        .IsUnique();

                    b.ToTable("preference_entries", "profiles");
                });

            modelBuilder.Entity("KitchenFlow.Infrastructure.Persistence.PreparationBatchRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeclaredYieldAvailabilityState")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal?>("DeclaredYieldMeasuredValue")
                        .HasColumnType("numeric(18,3)");

                    b.Property<string>("DeclaredYieldMeasuredUnit")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("OutputProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("PreparedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("OutputProductId", "OwnerUserId");

                    b.HasIndex("OwnerUserId", "PreparedAt", "Id");

                    b.ToTable("preparation_batches", "inventory", t =>
                        {
                            t.HasCheckConstraint("ck_preparation_batches_declared_yield", "(\"DeclaredYieldMeasuredValue\" IS NOT NULL AND \"DeclaredYieldMeasuredValue\" > 0 AND \"DeclaredYieldMeasuredUnit\" IN ('Gram', 'Milliliter', 'Unit') AND \"DeclaredYieldAvailabilityState\" IS NULL) OR (\"DeclaredYieldMeasuredValue\" IS NULL AND \"DeclaredYieldMeasuredUnit\" IS NULL AND \"DeclaredYieldAvailabilityState\" IN ('Available', 'Low', 'Unavailable'))");

                            t.HasCheckConstraint("ck_preparation_batches_prepared_at", "\"PreparedAt\" <= \"CreatedAt\"");

                            t.HasCheckConstraint("ck_preparation_batches_source", "\"SourceType\" IN ('ManualPreparation')");
                        });
                });

            modelBuilder.Entity("KitchenFlow.Infrastructure.Persistence.PreparationInputRecord", b =>
                {
                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("InputLotId")
                        .HasColumnType("uuid");

                    b.Property<string>("ConsumedUnit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("ConsumedValue")
                        .HasColumnType("numeric(18,3)");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.HasKey("BatchId", "InputLotId");

                    b.HasIndex("BatchId", "OwnerUserId");

                    b.HasIndex("InputLotId", "OwnerUserId");

                    b.HasIndex("OwnerUserId", "InputLotId");

                    b.ToTable("preparation_inputs", "inventory", t =>
                        {
                            t.HasCheckConstraint("ck_preparation_inputs_quantity", "\"ConsumedValue\" > 0 AND \"ConsumedUnit\" IN ('Gram', 'Milliliter', 'Unit')");
                        });
                });

            modelBuilder.Entity("KitchenFlow.Infrastructure.Persistence.PreparationOutputRecord", b =>
                {
                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OutputLotId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.HasKey("BatchId", "OutputLotId");

                    b.HasIndex("BatchId", "OwnerUserId");

                    b.HasIndex("OutputLotId", "OwnerUserId");

                    b.HasIndex("OwnerUserId", "OutputLotId")
                        .IsUnique();

                    b.ToTable("preparation_outputs", "inventory");
                });

            modelBuilder.Entity("KitchenFlow.Infrastructure.Persistence.PreparedLotRecord", b =>
                {
                    b.Property<Guid>("LotId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid");

                    b.Property<string>("LifecycleState")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTimeOffset>("PreparedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ShelfLifeConditions")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ShelfLifeConfidence")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateOnly?>("ShelfLifeDate")
                        .HasColumnType("date");

                    b.Property<string>("ShelfLifeSource")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("LotId", "OwnerUserId");

                    b.HasIndex("BatchId", "OwnerUserId");

                    b.HasIndex("OwnerUserId", "BatchId");

                    b.ToTable("prepared_lots", "inventory", t =>
                        {
                            t.HasCheckConstraint("ck_prepared_lots_evidence", "(\"ShelfLifeSource\" = 'Unknown' AND \"ShelfLifeDate\" IS NULL AND \"ShelfLifeConfidence\" = 'Unknown') OR (\"ShelfLifeSource\" IN ('UserEntered', 'Curated', 'Regional') AND \"ShelfLifeDate\" IS NOT NULL AND \"ShelfLifeConfidence\" IN ('Low', 'Medium', 'High'))");

                            t.HasCheckConstraint("ck_prepared_lots_lifecycle", "\"LifecycleState\" IN ('Prepared')");
                        });
                });

            modelBuilder.Entity("KitchenFlow.Infrastructure.Persistence.ProductRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("NormalizedSearchName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("products", "inventory", t =>
                        {
                            t.HasCheckConstraint("ck_products_display_name", "length(btrim(\"DisplayName\")) > 0");

                            t.HasCheckConstraint("ck_products_normalized_search_name", "length(btrim(\"NormalizedSearchName\")) > 0");
                        });
                });

            modelBuilder.Entity("KitchenFlow.Infrastructure.Persistence.ProfileChangeHistoryEntryRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FieldCodesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("SectionChanged")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId", "OccurredAt");

                    b.ToTable("change_history", "profiles");
                });

            modelBuilder.Entity("KitchenFlow.Infrastructure.Persistence.ProfileOrderedCodeEntryRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ListName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("StableCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId", "ListName", "SortOrder");

                    b.ToTable("ordered_code_entries", "profiles");
                });

            modelBuilder.Entity("KitchenFlow.Infrastructure.Persistence.TransactionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IdempotencyKey")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LotId")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("PreviousAvailabilityState")
                        .HasColumnType("text");

                    b.Property<string>("PreviousMeasuredUnit")
                        .HasColumnType("text");

                    b.Property<decimal?>("PreviousMeasuredValue")
                        .HasColumnType("numeric(18,3)");

                    b.Property<string>("ReasonCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ResultingAvailabilityState")
                        .HasColumnType("text");

                    b.Property<string>("ResultingMeasuredUnit")
                        .HasColumnType("text");

                    b.Property<decimal?>("ResultingMeasuredValue")
                        .HasColumnType("numeric(18,3)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("LotId", "OwnerUserId");

                    b.HasIndex("OwnerUserId", "LotId", "OccurredAt");

                    b.ToTable("transactions", "inventory", t =>
                        {
                            t.HasCheckConstraint("ck_transactions_previous_quantity", "(\"PreviousMeasuredValue\" IS NULL AND \"PreviousMeasuredUnit\" IS NULL AND \"PreviousAvailabilityState\" IS NULL) OR (\"PreviousMeasuredValue\" IS NOT NULL AND \"PreviousMeasuredValue\" >= 0 AND \"PreviousMeasuredUnit\" IN ('Gram', 'Milliliter', 'Unit') AND \"PreviousAvailabilityState\" IS NULL) OR (\"PreviousMeasuredValue\" IS NULL AND \"PreviousMeasuredUnit\" IS NULL AND \"PreviousAvailabilityState\" IN ('Available', 'Low', 'Unavailable'))");

                            t.HasCheckConstraint("ck_transactions_reason_code", "\"ReasonCode\" IS NULL OR length(btrim(\"ReasonCode\")) > 0");

                            t.HasCheckConstraint("ck_transactions_resulting_quantity", "(\"ResultingMeasuredValue\" IS NOT NULL AND \"ResultingMeasuredValue\" >= 0 AND \"ResultingMeasuredUnit\" IN ('Gram', 'Milliliter', 'Unit') AND \"ResultingAvailabilityState\" IS NULL) OR (\"ResultingMeasuredValue\" IS NULL AND \"ResultingMeasuredUnit\" IS NULL AND \"ResultingAvailabilityState\" IN ('Available', 'Low', 'Unavailable'))");

                            t.HasCheckConstraint("ck_transactions_type", "\"Type\" IN ('Initial', 'Consume', 'Discard', 'Correct', 'AvailabilityChanged', 'Deleted', 'PreparationInputConsumed', 'PreparationOutputCreated')");
                        });
                });

            modelBuilder.Entity("KitchenFlow.Infrastructure.Persistence.UserProfileRecord", b =>
                {
                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<bool?>("AdultDeclared")
                        .HasColumnType("boolean");

                    b.Property<string>("CleanupTolerance")
                        .HasColumnType("text");

                    b.Property<string>("CleanupTolerancePresence")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ConcurrencyToken")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Confidence")
                        .HasColumnType("text");

                    b.Property<string>("ConfidencePresence")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("CurrencyPresence")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("DefaultAdultCount")
                        .HasColumnType("integer");

                    b.Property<string>("DefaultAdultCountPresence")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("DefaultChildCount")
                        .HasColumnType("integer");

                    b.Property<string>("DefaultChildCountPresence")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("DefaultServingCount")
                        .HasColumnType("integer");

                    b.Property<string>("DefaultServingCountPresence")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("DisplayNamePresence")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("EffortTolerance")
                        .HasColumnType("text");

                    b.Property<string>("EffortTolerancePresence")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ExceptionalPrepMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("ExceptionalPrepMinutesPresence")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FreezingPreference")
                        .HasColumnType("text");

                    b.Property<string>("FreezingPreferencePresence")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Language")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("LanguagePresence")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LeftoverPreference")
                        .HasColumnType("text");

                    b.Property<string>("LeftoverPreferencePresence")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MeasurementSystem")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("MeasurementSystemPresence")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("OrdinaryPrepMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("OrdinaryPrepMinutesPresence")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OverallSkill")
                        .HasColumnType("text");

                    b.Property<string>("OverallSkillPresence")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlanningCadence")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PlanningCadencePresence")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PreferredInstructionDetail")
                        .HasColumnType("text");

                    b.Property<string>("PreferredInstructionDetailPresence")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrivacyVersion")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Region")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("RegionPresence")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReheatingPreference")
                        .HasColumnType("text");

                    b.Property<string>("ReheatingPreferencePresence")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RepeatMealPreference")
                        .HasColumnType("text");

                    b.Property<string>("RepeatMealPreferencePresence")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShoppingCadence")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ShoppingCadencePresence")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("TermsAcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TermsVersion")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("TimeZone")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("TimeZonePresence")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("OwnerUserId");

                    b.HasIndex("ConcurrencyToken")
                        .IsUnique();

                    b.ToTable("user_profiles", "profiles", t =>
                        {
                            t.HasCheckConstraint("ck_profiles_currency", "\"Currency\" IS NULL OR \"Currency\" IN ('USD', 'BRL', 'EUR')");

                            t.HasCheckConstraint("ck_profiles_default_adult_count", "\"DefaultAdultCount\" IS NULL OR (\"DefaultAdultCount\" BETWEEN 1 AND 20)");

                            t.HasCheckConstraint("ck_profiles_default_child_count", "\"DefaultChildCount\" IS NULL OR (\"DefaultChildCount\" BETWEEN 0 AND 20)");

                            t.HasCheckConstraint("ck_profiles_default_serving_count", "\"DefaultServingCount\" IS NULL OR (\"DefaultServingCount\" BETWEEN 1 AND 30)");

                            t.HasCheckConstraint("ck_profiles_language", "\"Language\" IS NULL OR \"Language\" IN ('en', 'pt-BR', 'es')");

                            t.HasCheckConstraint("ck_profiles_measurement_system", "\"MeasurementSystem\" IS NULL OR \"MeasurementSystem\" IN ('Metric', 'UsCustomary')");

                            t.HasCheckConstraint("ck_profiles_region", "\"Region\" IS NULL OR \"Region\" IN ('US', 'BR', 'ES')");
                        });
                });

            modelBuilder.Entity("KitchenFlow.Modules.Identity.InternalUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("Issuer", "Subject")
                        .IsUnique();

                    b.ToTable("users", "identity");
                });

            modelBuilder.Entity("KitchenFlow.Infrastructure.Persistence.AuditEventRecord", b =>
                {
                    b.HasOne("KitchenFlow.Modules.Identity.InternalUser", null)
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("KitchenFlow.Infrastructure.Persistence.EquipmentEntryRecord", b =>
                {
                    b.HasOne("KitchenFlow.Infrastructure.Persistence.UserProfileRecord", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KitchenFlow.Infrastructure.Persistence.IdempotencyRecord", b =>
                {
                    b.HasOne("KitchenFlow.Modules.Identity.InternalUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("KitchenFlow.Infrastructure.Persistence.LotRecord", b =>
                {
                    b.HasOne("KitchenFlow.Modules.Identity.InternalUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KitchenFlow.Infrastructure.Persistence.ProductRecord", null)
                        .WithMany()
                        .HasForeignKey("ProductId", "OwnerUserId")
                        .HasPrincipalKey("Id", "OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("KitchenFlow.Infrastructure.Persistence.PreferenceEntryRecord", b =>
                {
                    b.HasOne("KitchenFlow.Infrastructure.Persistence.UserProfileRecord", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KitchenFlow.Infrastructure.Persistence.PreparationBatchRecord", b =>
                {
                    b.HasOne("KitchenFlow.Modules.Identity.InternalUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KitchenFlow.Infrastructure.Persistence.ProductRecord", null)
                        .WithMany()
                        .HasForeignKey("OutputProductId", "OwnerUserId")
                        .HasPrincipalKey("Id", "OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("KitchenFlow.Infrastructure.Persistence.PreparationInputRecord", b =>
                {
                    b.HasOne("KitchenFlow.Infrastructure.Persistence.PreparationBatchRecord", null)
                        .WithMany()
                        .HasForeignKey("BatchId", "OwnerUserId")
                        .HasPrincipalKey("Id", "OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KitchenFlow.Infrastructure.Persistence.LotRecord", null)
                        .WithMany()
                        .HasForeignKey("InputLotId", "OwnerUserId")
                        .HasPrincipalKey("Id", "OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("KitchenFlow.Infrastructure.Persistence.PreparationOutputRecord", b =>
                {
                    b.HasOne("KitchenFlow.Infrastructure.Persistence.PreparationBatchRecord", null)
                        .WithMany()
                        .HasForeignKey("BatchId", "OwnerUserId")
                        .HasPrincipalKey("Id", "OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KitchenFlow.Infrastructure.Persistence.LotRecord", null)
                        .WithMany()
                        .HasForeignKey("OutputLotId", "OwnerUserId")
                        .HasPrincipalKey("Id", "OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("KitchenFlow.Infrastructure.Persistence.PreparedLotRecord", b =>
                {
                    b.HasOne("KitchenFlow.Infrastructure.Persistence.PreparationBatchRecord", null)
                        .WithMany()
                        .HasForeignKey("BatchId", "OwnerUserId")
                        .HasPrincipalKey("Id", "OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KitchenFlow.Infrastructure.Persistence.LotRecord", null)
                        .WithMany()
                        .HasForeignKey("LotId", "OwnerUserId")
                        .HasPrincipalKey("Id", "OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("KitchenFlow.Infrastructure.Persistence.ProductRecord", b =>
                {
                    b.HasOne("KitchenFlow.Modules.Identity.InternalUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("KitchenFlow.Infrastructure.Persistence.ProfileChangeHistoryEntryRecord", b =>
                {
                    b.HasOne("KitchenFlow.Infrastructure.Persistence.UserProfileRecord", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KitchenFlow.Infrastructure.Persistence.ProfileOrderedCodeEntryRecord", b =>
                {
                    b.HasOne("KitchenFlow.Infrastructure.Persistence.UserProfileRecord", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KitchenFlow.Infrastructure.Persistence.TransactionRecord", b =>
                {
                    b.HasOne("KitchenFlow.Modules.Identity.InternalUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KitchenFlow.Infrastructure.Persistence.LotRecord", null)
                        .WithMany()
                        .HasForeignKey("LotId", "OwnerUserId")
                        .HasPrincipalKey("Id", "OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("KitchenFlow.Infrastructure.Persistence.UserProfileRecord", b =>
                {
                    b.HasOne("KitchenFlow.Modules.Identity.InternalUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
