/** English (`en`) labels for profile catalog codes. See `./profileCatalog.ts`. */
import type { ProfileCatalogTable } from "./profileCatalog";

export const en: ProfileCatalogTable = {
  equipment: {
    oven: "Oven",
    stovetop: "Stovetop",
    microwave: "Microwave",
    refrigerator: "Refrigerator",
    freezer: "Freezer",
    slow_cooker: "Slow cooker",
    pressure_cooker: "Pressure cooker",
    air_fryer: "Air fryer",
    blender: "Blender",
    food_processor: "Food processor",
    stand_mixer: "Stand mixer",
    toaster_oven: "Toaster oven",
    outdoor_grill: "Outdoor grill",
    rice_cooker: "Rice cooker",
    sous_vide_immersion_circulator: "Sous vide immersion circulator",
  },
  technique: {
    knife_skills: "Knife skills",
    sauteing: "Sautéing",
    roasting: "Roasting",
    baking: "Baking",
    grilling: "Grilling",
    braising: "Braising",
    steaming: "Steaming",
    deep_frying: "Deep frying",
    poaching: "Poaching",
    fermenting: "Fermenting",
    sous_vide_cooking: "Sous vide cooking",
    pressure_cooking: "Pressure cooking",
    stir_frying: "Stir frying",
    blanching: "Blanching",
  },
  goal: {
    eat_healthier: "Eat healthier",
    save_money: "Save money",
    reduce_food_waste: "Reduce food waste",
    save_time: "Save time",
    learn_new_skills: "Learn new skills",
    meal_prep_ahead: "Meal prep ahead",
    cook_more_at_home: "Cook more at home",
    eat_more_variety: "Eat more variety",
    reduce_takeout: "Reduce takeout",
    feed_family_easier: "Feed my family more easily",
    build_confidence: "Build cooking confidence",
  },
  abandonmentReason: {
    too_time_consuming: "Too time-consuming",
    too_expensive: "Too expensive",
    lack_of_ingredients: "Lack of ingredients",
    lost_interest: "Lost interest",
    life_change: "Life change",
    meal_plan_did_not_fit: "Meal plan didn't fit my routine",
    recipes_too_complex: "Recipes were too complex",
    not_enough_variety: "Not enough variety",
    technical_issues: "Technical issues",
    preferred_takeout: "Preferred takeout",
  },
  Preference: {
    spicy_food: "Spicy food",
    comfort_food: "Comfort food",
    fresh_vegetables: "Fresh vegetables",
    grilled_flavors: "Grilled flavors",
    one_pot_meals: "One-pot meals",
    baked_goods: "Baked goods",
    street_food_style: "Street-food style",
    slow_cooked_meals: "Slow-cooked meals",
  },
  Dislike: {
    cilantro: "Cilantro",
    mushrooms: "Mushrooms",
    olives: "Olives",
    blue_cheese: "Blue cheese",
    liver: "Liver",
    raw_onion: "Raw onion",
    licorice: "Licorice",
    anchovies: "Anchovies",
  },
  DietaryPattern: {
    vegetarian: "Vegetarian",
    vegan: "Vegan",
    pescatarian: "Pescatarian",
    keto: "Keto",
    paleo: "Paleo",
    gluten_free_diet: "Gluten-free",
    dairy_free_diet: "Dairy-free",
    low_carb: "Low-carb",
    mediterranean_diet: "Mediterranean diet",
  },
  Intolerance: {
    lactose_intolerance: "Lactose intolerance",
    gluten_intolerance: "Gluten intolerance",
    fructose_intolerance: "Fructose intolerance",
    histamine_intolerance: "Histamine intolerance",
    caffeine_sensitivity: "Caffeine sensitivity",
    sulfite_sensitivity: "Sulfite sensitivity",
  },
  Allergy: {
    peanut_allergy: "Peanut allergy",
    tree_nut_allergy: "Tree nut allergy",
    shellfish_allergy: "Shellfish allergy",
    fish_allergy: "Fish allergy",
    egg_allergy: "Egg allergy",
    milk_allergy: "Milk allergy",
    soy_allergy: "Soy allergy",
    wheat_allergy: "Wheat allergy",
    sesame_allergy: "Sesame allergy",
  },
  ReligiousRestriction: {
    halal: "Halal",
    kosher: "Kosher",
    hindu_vegetarian: "Hindu vegetarian",
    jain_diet: "Jain diet",
    lent_fasting: "Lent fasting",
    buddhist_vegetarian: "Buddhist vegetarian",
  },
  EthicalRestriction: {
    vegan_ethical: "Ethical veganism",
    cruelty_free_only: "Cruelty-free only",
    sustainable_seafood_only: "Sustainable seafood only",
    fair_trade_only: "Fair trade only",
    local_sourcing_preferred: "Local sourcing preferred",
    no_palm_oil: "No palm oil",
  },
  MedicalRestriction: {
    low_sodium_diet: "Low-sodium diet",
    low_sugar_diet: "Low-sugar diet",
    renal_diet: "Renal diet",
    low_fodmap_diet: "Low-FODMAP diet",
    celiac_safe_diet: "Celiac-safe diet",
    heart_healthy_diet: "Heart-healthy diet",
    diabetic_friendly_diet: "Diabetic-friendly diet",
  },
};
