/** Brazilian Portuguese (`pt-BR`) labels for profile catalog codes. See `./profileCatalog.ts`. */
import type { ProfileCatalogTable } from "./profileCatalog";

export const ptBR: ProfileCatalogTable = {
  equipment: {
    oven: "Forno",
    stovetop: "Fogão",
    microwave: "Micro-ondas",
    refrigerator: "Geladeira",
    freezer: "Freezer",
    slow_cooker: "Panela de cozimento lento",
    pressure_cooker: "Panela de pressão",
    air_fryer: "Fritadeira sem óleo (air fryer)",
    blender: "Liquidificador",
    food_processor: "Processador de alimentos",
    stand_mixer: "Batedeira de bancada",
    toaster_oven: "Forno elétrico de bancada",
    outdoor_grill: "Churrasqueira",
    rice_cooker: "Panela elétrica de arroz",
    sous_vide_immersion_circulator: "Circulador de imersão (sous vide)",
  },
  technique: {
    knife_skills: "Técnicas de faca",
    sauteing: "Refogar",
    roasting: "Assar em forno alto",
    baking: "Assar",
    grilling: "Grelhar",
    braising: "Fazer refogado longo (braseado)",
    steaming: "Cozinhar no vapor",
    deep_frying: "Fritar por imersão",
    poaching: "Escalfar",
    fermenting: "Fermentar",
    sous_vide_cooking: "Cozinhar em sous vide",
    pressure_cooking: "Cozinhar na panela de pressão",
    stir_frying: "Refogar em fogo alto (stir-fry)",
    blanching: "Branquear",
  },
  goal: {
    eat_healthier: "Comer de forma mais saudável",
    save_money: "Economizar dinheiro",
    reduce_food_waste: "Reduzir desperdício de comida",
    save_time: "Economizar tempo",
    learn_new_skills: "Aprender novas habilidades",
    meal_prep_ahead: "Preparar refeições com antecedência",
    cook_more_at_home: "Cozinhar mais em casa",
    eat_more_variety: "Comer com mais variedade",
    reduce_takeout: "Reduzir pedidos de comida pronta",
    feed_family_easier: "Alimentar a família com mais facilidade",
    build_confidence: "Ganhar confiança na cozinha",
  },
  abandonmentReason: {
    too_time_consuming: "Consumia muito tempo",
    too_expensive: "Muito caro",
    lack_of_ingredients: "Falta de ingredientes",
    lost_interest: "Perdeu o interesse",
    life_change: "Mudança na rotina de vida",
    meal_plan_did_not_fit: "O plano de refeições não se encaixou na rotina",
    recipes_too_complex: "Receitas muito complexas",
    not_enough_variety: "Pouca variedade",
    technical_issues: "Problemas técnicos",
    preferred_takeout: "Preferiu comida pronta",
  },
  Preference: {
    spicy_food: "Comida apimentada",
    comfort_food: "Comida reconfortante",
    fresh_vegetables: "Vegetais frescos",
    grilled_flavors: "Sabores grelhados",
    one_pot_meals: "Refeições de panela única",
    baked_goods: "Assados",
    street_food_style: "Estilo comida de rua",
    slow_cooked_meals: "Refeições de cozimento lento",
  },
  Dislike: {
    cilantro: "Coentro",
    mushrooms: "Cogumelos",
    olives: "Azeitonas",
    blue_cheese: "Queijo azul",
    liver: "Fígado",
    raw_onion: "Cebola crua",
    licorice: "Alcaçuz",
    anchovies: "Anchovas",
  },
  DietaryPattern: {
    vegetarian: "Vegetariano",
    vegan: "Vegano",
    pescatarian: "Pescetariano",
    keto: "Cetogênica",
    paleo: "Paleolítica",
    gluten_free_diet: "Sem glúten",
    dairy_free_diet: "Sem laticínios",
    low_carb: "Baixo carboidrato",
    mediterranean_diet: "Dieta mediterrânea",
  },
  Intolerance: {
    lactose_intolerance: "Intolerância à lactose",
    gluten_intolerance: "Intolerância ao glúten",
    fructose_intolerance: "Intolerância à frutose",
    histamine_intolerance: "Intolerância à histamina",
    caffeine_sensitivity: "Sensibilidade à cafeína",
    sulfite_sensitivity: "Sensibilidade a sulfitos",
  },
  Allergy: {
    peanut_allergy: "Alergia a amendoim",
    tree_nut_allergy: "Alergia a castanhas",
    shellfish_allergy: "Alergia a frutos do mar",
    fish_allergy: "Alergia a peixe",
    egg_allergy: "Alergia a ovo",
    milk_allergy: "Alergia a leite",
    soy_allergy: "Alergia a soja",
    wheat_allergy: "Alergia a trigo",
    sesame_allergy: "Alergia a gergelim",
  },
  ReligiousRestriction: {
    halal: "Halal",
    kosher: "Kosher",
    hindu_vegetarian: "Vegetarianismo hindu",
    jain_diet: "Dieta jainista",
    lent_fasting: "Jejum da quaresma",
    buddhist_vegetarian: "Vegetarianismo budista",
  },
  EthicalRestriction: {
    vegan_ethical: "Veganismo por convicção ética",
    cruelty_free_only: "Somente produtos cruelty-free",
    sustainable_seafood_only: "Somente frutos do mar sustentáveis",
    fair_trade_only: "Somente comércio justo",
    local_sourcing_preferred: "Preferência por produção local",
    no_palm_oil: "Sem óleo de palma",
  },
  MedicalRestriction: {
    low_sodium_diet: "Dieta com baixo teor de sódio",
    low_sugar_diet: "Dieta com baixo teor de açúcar",
    renal_diet: "Dieta renal",
    low_fodmap_diet: "Dieta baixa em FODMAP",
    celiac_safe_diet: "Dieta segura para celíacos",
    heart_healthy_diet: "Dieta para saúde do coração",
    diabetic_friendly_diet: "Dieta para diabéticos",
  },
};
