/** Spanish (`es`) labels for profile catalog codes. See `./profileCatalog.ts`. */
import type { ProfileCatalogTable } from "./profileCatalog";

export const es: ProfileCatalogTable = {
  equipment: {
    oven: "Horno",
    stovetop: "Estufa",
    microwave: "Microondas",
    refrigerator: "Refrigerador",
    freezer: "Congelador",
    slow_cooker: "Olla de cocción lenta",
    pressure_cooker: "Olla a presión",
    air_fryer: "Freidora de aire",
    blender: "Licuadora",
    food_processor: "Procesador de alimentos",
    stand_mixer: "Batidora de pie",
    toaster_oven: "Horno tostador",
    outdoor_grill: "Parrilla",
    rice_cooker: "Olla eléctrica de arroz",
    sous_vide_immersion_circulator: "Circulador de inmersión (sous vide)",
  },
  technique: {
    knife_skills: "Técnicas de cuchillo",
    sauteing: "Salteado",
    roasting: "Asado al horno",
    baking: "Horneado",
    grilling: "A la parrilla",
    braising: "Estofado",
    steaming: "Cocción al vapor",
    deep_frying: "Fritura profunda",
    poaching: "Escalfado",
    fermenting: "Fermentación",
    sous_vide_cooking: "Cocción sous vide",
    pressure_cooking: "Cocción a presión",
    stir_frying: "Salteado rápido (stir-fry)",
    blanching: "Escaldado",
  },
  goal: {
    eat_healthier: "Comer de forma más saludable",
    save_money: "Ahorrar dinero",
    reduce_food_waste: "Reducir el desperdicio de comida",
    save_time: "Ahorrar tiempo",
    learn_new_skills: "Aprender nuevas habilidades",
    meal_prep_ahead: "Preparar comidas con antelación",
    cook_more_at_home: "Cocinar más en casa",
    eat_more_variety: "Comer con más variedad",
    reduce_takeout: "Reducir la comida para llevar",
    feed_family_easier: "Alimentar a la familia más fácilmente",
    build_confidence: "Ganar confianza al cocinar",
  },
  abandonmentReason: {
    too_time_consuming: "Consumía demasiado tiempo",
    too_expensive: "Demasiado costoso",
    lack_of_ingredients: "Falta de ingredientes",
    lost_interest: "Perdió el interés",
    life_change: "Cambio en la rutina de vida",
    meal_plan_did_not_fit: "El plan de comidas no se ajustó a mi rutina",
    recipes_too_complex: "Recetas demasiado complejas",
    not_enough_variety: "Poca variedad",
    technical_issues: "Problemas técnicos",
    preferred_takeout: "Prefirió comida para llevar",
  },
  Preference: {
    spicy_food: "Comida picante",
    comfort_food: "Comida reconfortante",
    fresh_vegetables: "Vegetales frescos",
    grilled_flavors: "Sabores a la parrilla",
    one_pot_meals: "Comidas de una sola olla",
    baked_goods: "Productos horneados",
    street_food_style: "Estilo comida callejera",
    slow_cooked_meals: "Comidas de cocción lenta",
  },
  Dislike: {
    cilantro: "Cilantro",
    mushrooms: "Champiñones",
    olives: "Aceitunas",
    blue_cheese: "Queso azul",
    liver: "Hígado",
    raw_onion: "Cebolla cruda",
    licorice: "Regaliz",
    anchovies: "Anchoas",
  },
  DietaryPattern: {
    vegetarian: "Vegetariano",
    vegan: "Vegano",
    pescatarian: "Pescetariano",
    keto: "Cetogénica",
    paleo: "Paleo",
    gluten_free_diet: "Sin gluten",
    dairy_free_diet: "Sin lácteos",
    low_carb: "Baja en carbohidratos",
    mediterranean_diet: "Dieta mediterránea",
  },
  Intolerance: {
    lactose_intolerance: "Intolerancia a la lactosa",
    gluten_intolerance: "Intolerancia al gluten",
    fructose_intolerance: "Intolerancia a la fructosa",
    histamine_intolerance: "Intolerancia a la histamina",
    caffeine_sensitivity: "Sensibilidad a la cafeína",
    sulfite_sensitivity: "Sensibilidad a los sulfitos",
  },
  Allergy: {
    peanut_allergy: "Alergia al maní",
    tree_nut_allergy: "Alergia a los frutos secos",
    shellfish_allergy: "Alergia a los mariscos",
    fish_allergy: "Alergia al pescado",
    egg_allergy: "Alergia al huevo",
    milk_allergy: "Alergia a la leche",
    soy_allergy: "Alergia a la soja",
    wheat_allergy: "Alergia al trigo",
    sesame_allergy: "Alergia al sésamo",
  },
  ReligiousRestriction: {
    halal: "Halal",
    kosher: "Kosher",
    hindu_vegetarian: "Vegetarianismo hindú",
    jain_diet: "Dieta jainista",
    lent_fasting: "Ayuno de cuaresma",
    buddhist_vegetarian: "Vegetarianismo budista",
  },
  EthicalRestriction: {
    vegan_ethical: "Veganismo ético",
    cruelty_free_only: "Solo productos cruelty-free",
    sustainable_seafood_only: "Solo mariscos sostenibles",
    fair_trade_only: "Solo comercio justo",
    local_sourcing_preferred: "Preferencia por producción local",
    no_palm_oil: "Sin aceite de palma",
  },
  MedicalRestriction: {
    low_sodium_diet: "Dieta baja en sodio",
    low_sugar_diet: "Dieta baja en azúcar",
    renal_diet: "Dieta renal",
    low_fodmap_diet: "Dieta baja en FODMAP",
    celiac_safe_diet: "Dieta segura para celíacos",
    heart_healthy_diet: "Dieta para la salud del corazón",
    diabetic_friendly_diet: "Dieta apta para diabéticos",
  },
};
