<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/KitchenFlow.Api/KitchenFlow.Api.csproj" />
    <ProjectReference Include="../../src/KitchenFlow.Infrastructure/KitchenFlow.Infrastructure.csproj" />
    <ProjectReference Include="../../src/KitchenFlow.Modules.Identity/KitchenFlow.Modules.Identity.csproj" />
    <ProjectReference Include="../../src/KitchenFlow.Modules.Inventory/KitchenFlow.Modules.Inventory.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NetArchTest.Rules" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
